services:
    # app
    app:
        build:
            args:
                user: admin
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/:/usr/local/etc/php/conf.d/
        depends_on: 
            - nginx
            - db
        networks: 
            - network

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8000:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - network

    # db
    db:
        image: mysql:latest
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: dbbroutlet
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: broutlet
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - 3308:3306
        networks: 
            - network

    # phpmyadmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db  # Conecta ao contêiner do MySQL
            PMA_PORT: 3306
            PMA_ARBITRARY: 1  # Permite conectar a qualquer banco de dados
        ports:
            - 8080:80
        depends_on:
            - db
        networks:
            - network

networks: 
    network:
        driver: bridge